---
- name: Run local discovery script on remote host
  hosts: all
  remote_user: root
  tasks:
    - name: Get hostname
      ansible.builtin.shell: hostname
      register: hostname_output

    - name: Get IP address (first non-loopback)
      ansible.builtin.shell: hostname -I | awk '{print $1}'
      register: ip_output

    - name: Set filename using hostname and IP (dots replaced with underscores)
      set_fact:
        custom_filename: "{{ hostname_output.stdout | regex_replace('\\.', '_') | regex_replace('\\-', '_') }}_{{ ip_output.stdout | regex_replace('\\.', '_') }}.csv"

    - name: Execute local script on remote machine
      ansible.builtin.script: ./info.sh "./{{ custom_filename }}"

    - name: Upload file using curl to WebDAV
      ansible.builtin.command: >
        curl -T "./{{ custom_filename }}" -u {{ user }}:{{ pass }} {{ link }}

    - name: clean-up at end (delete file)
      ansible.builtin.file:
        path: "./{{ custom_filename }}"
        state: absent
